[dependencies]

[package]
  cjc-version = "0.53.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "cache"
  output-type = "static"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
